index/urls.py
from django.urls import path, include
from .views import index, profile, user_logout, AppLoginView,UpdateUserView,travels,about,travel,register_user,chats,message,folder,folderCreate,users,tarifs,friends,favorites,trips,trip
from trips.views import travelers,create_trip,trip_boocking,close_boocking,close_trip
from travels.views import create_travel
from chat.views import private_chat, send_message, display_messages
from users.views import addToFriends, addFavorites, create_payment, activate_premium
from users.decorators import check_recaptcha
from blog.views import blog, post, toggle_like

urlpatterns = [
    path('', index, name='index'),
    path('travelers/', travelers, name='travelers'),
    path('about/', about, name='about'),
    path('tarifs/', tarifs, name='tarifs'),
    path('friends/', friends, name='friends'),
    path('favorits/', favorites, name='favorits'),
    path('profile/<user_id>/', profile, name='profile'),
    path('profile/settings/<int:user_id>/', UpdateUserView.as_view(), name='update_user'),
    path('logout/', user_logout, name='logout'),
    path('login/', AppLoginView.as_view(), name='custom_login'),
    path('registration/', check_recaptcha(register_user), name='register_user'),
    path('travels/', travels, name='travels'),
    path('trips/', trips, name='trips'),
    path('trip_boocking/<int:trip_id>/', trip_boocking, name='trip_boocking'),
    path('close_boocking/<int:trip_id>/', close_boocking, name='close_boocking'),
    path('close_trip/<int:trip_id>/', close_trip, name='close_trip'),
    path('users/', users, name='users'),
    path('travel/<travel_id>/', travel, name='travel'),
    path('trip/<trip_id>/', trip, name='trip'),
    path('create_travel', create_travel, name='create_travel'),
    path('create_trip/', create_trip, name='create_trip'),
    path('chats/', chats, name='chats'),
    path('chats/folder/<int:folder_id>/', folder, name='folder'),
    path('chats/folderCreate/', folderCreate, name='folderCreate'),
    path('chats/message/<int:recipient_id>/', message, name='message'),        
    path('private_chat/<int:recipient_id>/', private_chat, name='private_chat'),
    path('send_message/<int:recipient_id>/', send_message, name='send_message'),
    path('display_messages/<int:recipient_id>/', display_messages, name='display_messages'),
    path('add_friend/<int:user_id>/', addToFriends, name="addToFriends"),
    path('add_favorites/<int:user_id>/', addFavorites, name="addFavorites"),
    # path('display_messages/<int:recipient_id>/', display_messages, name='display_messages'),
    path('blog/', blog, name='blog'),
    path('blog/<int:post_id>/', post, name='post'),
    path('toggle_like/<int:post_id>/', toggle_like, name='toggle_like'),
    path('create-payment/', create_payment, name='create_payment'),
    path('activate_premium/', activate_premium, name='activate_premium'),
]

travelo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework import routers, permissions
from rest_framework.routers import DefaultRouter
from users.views import CustomUserViewSet, InterestsViewSet, HabitsViewSet, JWTLoginView, JWTRegisterView, JWTLogoutView, UserProfileInfoView
from travels.views import TravelViewSet, CountryViewSet, TravelViewSetFromMoscow, TravelListAPIView, CityViewSet, TravelFilterView, TravelFilterInfoView
from trips.views import TripFilterView, TripFilterInfoView, TriplViewSet

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

router = routers.DefaultRouter()
router.register(r'users', CustomUserViewSet)
router.register(r'travels', TravelViewSet)
router.register(r'trips', TriplViewSet)
router.register(r'countries', CountryViewSet)
router.register(r'cities', CityViewSet)
router.register(r'interests', InterestsViewSet)
router.register(r'habits', HabitsViewSet)
router.register(r'from_moscow', TravelViewSetFromMoscow, basename="from_moscow")


from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="TRAVELO API",
      default_version='v1',
      description="API Для сайта Travelo",
      terms_of_service="https://www.example.com/policies/terms/",
      contact=openapi.Contact(email="contact@example.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

from chat import views as chat_views
from django.urls import re_path
from trips.views import UserTripsFilterInfoView
from travels.views import UserTravelsFilterInfoView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), #  <- include the allauth urls here
    path('', include('index.urls')),
    path('api/', include(router.urls)),
    path('api/login/', JWTLoginView.as_view(), name='jwt_login'),
    path('api/logout/', JWTLogoutView.as_view(), name='jwt_logout'),
    path('api/register/', JWTRegisterView.as_view(), name='jwt_register'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/profile-info/', UserProfileInfoView.as_view(), name='user_profile'),
    path('api/user/travels/<user_id>/', UserTravelsFilterInfoView.as_view(), name='user_travels'),
    path('api/user/trips/<user_id>/', UserTripsFilterInfoView.as_view(), name='user_trips'),
    # path('api/travels/filter/', TravelFilterView.as_view(), name='travel-filter'),    
    re_path(r'^api/travels/filter/?$', TravelFilterView.as_view(), name='travel-filter'),
    re_path(r'^api/travels/filter/info?$', TravelFilterInfoView.as_view(), name='travel-filter-info'),
    re_path(r'^api/trips/filter/?$', TripFilterView.as_view(), name='trips-filter'),
    re_path(r'^api/trips/filter/info?$', TripFilterInfoView.as_view(), name='trip-filter-info'),
    path('travels/list/', TravelListAPIView.as_view(), name='travel-list'),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # APIs
    # path('online-users/', chat_views.api_online_users, name='online-users'),
    # path('online-users/<int:id>', chat_views.api_online_users, name='online-users'),
    # path('chat-messages/<int:id>', chat_views.api_chat_messages, name='chat_messages'),
    # path('unread/', chat_views.api_unread, name='api_unread'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = settings.ADMIN_SITE_HEADER

travels/models.py
from django.db import models
from users.models import CustomUser, City
from django.db.models import Count
# Create your models here.

class Travel(models.Model):
    
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')

    MEN = 'Мужчина'
    GIRL = 'Женщина'

    GENDERS_LIST = [
        (MEN, 'Мужчина'),
        (GIRL, 'Женщина')
    ]


    SEARCH_MEN = 'Мужчину'
    SEARCH_GIRL = 'Женщину'
    SEARCH_FAMIlY = 'Семью'


    SEARCH_GENDERS_LIST = [
        (SEARCH_MEN, 'Мужчину'),
        (SEARCH_GIRL, 'Женщину'),
        (SEARCH_FAMIlY, 'Семью'),
    ]

    gender = models.CharField(max_length=15, choices=GENDERS_LIST, default=None, verbose_name='Пол', null=True, blank=True)
    gender_search = models.CharField(max_length=15, choices=SEARCH_GENDERS_LIST, default=None, verbose_name='Ищу', blank=True, null=True)
    city = models.CharField(max_length=200, verbose_name='Город, Курорт', blank=True, null=True)
    country = models.ManyToManyField('Country', related_name='travels', verbose_name='Страна')
    days = models.IntegerField(verbose_name='Количество дней', blank=True, null=True)
    date = models.DateField(verbose_name='Когда', blank=True, null=True)
    description = models.TextField(verbose_name='Описание путешествия', blank=True, null=True)
    travel_now = models.BooleanField(default=False, verbose_name='Уже путешествую', blank=True, null=True)
    from_city = models.ForeignKey(City, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Откуда')

    def __str__(self):
        return f''


    class Meta:
        verbose_name = "Путешествие"
        verbose_name_plural = "Путешествия"


class Country(models.Model):
    name = models.CharField(max_length=200, verbose_name='Страна', blank=True, null=True)
    image = models.ImageField(upload_to='countries/%Y/%m/%d/', blank=True, null=True)
    cities = models.ManyToManyField(City, related_name='city_countries', verbose_name='Города', blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'

    # @property
    # def travel_count(self):
    #     return self.travels.count()

    # @classmethod
    # def with_travel_counts(cls):
    #     return cls.objects.annotate(travel_count=Count('travels'))

trips/models.py
from django.db import models
from users.models import CustomUser, City, UserCar
# Create your models here.

class Trip(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    trip_users = models.ManyToManyField(CustomUser, related_name='trip_users', blank=True, null=True)
    # trip_date = models.DateTimeField(blank=True, null=True)
    free_seats = models.IntegerField(default=0, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, blank=True, null=True)
    price = models.IntegerField(default=0, blank=True, null=True)
    status = models.BooleanField(default=True, blank=True, null=True)
    finish = models.BooleanField(default=False, blank=True, null=True)
    cityin = models.ForeignKey(City, on_delete=models.CASCADE, related_name='citiin', blank=True, null=True)
    trip_in_time = models.DateTimeField(blank=True, null=True)
    trip_out_time = models.DateTimeField(blank=True, null=True)
    trip_car = models.ForeignKey(UserCar, on_delete=models.CASCADE, blank=True, null=True)
    # trip_baggage = models.BooleanField(default=False, blank=True, null=True)
    # trip_smoking = models.BooleanField(default=False, blank=True, null=True)
    # trip_hild_seat = models.BooleanField(default=False, blank=True, null=True)
    # trip_animals = models.BooleanField(default=False, blank=True, null=True)
    trip_others = models.ManyToManyField("TripOther", blank=True, null=True, related_name="trip_others")
    
    def __str__(self):
        return self.user.email
    
    class Meta:
        verbose_name = "Поездка"
        verbose_name_plural = "Поездки"
 
# class CarBrand(models.Model):
#     name = models.CharField(max_length=200)
#     image = models.ImageField(upload_to="cars/brands/%Y/%m/%d/")
    
# class UserCar(models.Model):
#     car = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
#     model = models.ForeignKey("CarModel", on_delete=models.CASCADE)

# class CarModel(models.Model):
#     name = models.CharField(max_length=200)

class TripOther(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="trips/others/%Y/%m/%d/")
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Дополнительная опция"
        verbose_name_plural = "Дополнительные опции"

travels/forms.py
from django import forms
from .models import Travel, Country

class TravelForm(forms.ModelForm):
    country = forms.ModelMultipleChoiceField(queryset=Country.objects.all(), required=False)

    class Meta:
        model = Travel
        fields = '__all__'
        exclude = ['user']  # Exclude the 'user' field from the form

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TravelForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(TravelForm, self).save(commit=False)
        instance.user = self.user
        if commit:
            instance.save()
            self.save_m2m()  # Save the many-to-many relationships
        return instance

class TravelersForm(forms.ModelForm):
    country = forms.ModelMultipleChoiceField(queryset=Country.objects.all(), required=False)

    class Meta:
        model = Travel
        fields = '__all__'
        exclude = ['user']  # Exclude the 'user' field from the form

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TravelersForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(TravelersForm, self).save(commit=False)
        instance.user = self.user
        if commit:
            instance.save()
            self.save_m2m()  # Save the many-to-many relationships
        return instance

templates/pages/create_travel.html
{% extends 'base_site.html' %}{% load static %}
{% block content %}
 <!-- <div class="wow animate__fadeInDown"></div> -->
 <form id="create_travel_window_script_form" action="{% url 'create_travel' %}" method="post" class="create-travel-form">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <h1>Создать путешествие</h1>
  <div class="create_travel_layer_content">
  <div class="form-user-info">
    <div>
      <label for="id_gender">Я</label>
      <select name="gender" id="id_gender">
        <option value="Мужчина">Мужчина</option>
        <option value="Женщина">Женщина</option>
      </select>
    </div>
  <div>
    <label for="id_gender_search">Ищу</label>
    <select name="gender_search" id="id_gender_search" required><option value="Семью">Семью</option>
      <option value="Женщину">Женщину</option>
      <option value="Мужчину">Мужчину</option>
    </select>
  </div><div class="from_city_link_layer" style="width: 100%;">
    <select name="from_city" id="id_from_city" class="js-chosen3" style="" required>
      {% for city in cities %}
          <option value="{{city.id}}">{{ city.name }}</option>
      {% endfor %}
      <option value="" selected disabled>Откуда?</option>
  </select>
  <style>
    
    .from_city_link_layer{}
    .from_city_link_layer a{
      width: 100%;
    padding: 15px!IMPORTANT;
    border-radius: 9px;
    border: 1px solid #00000045;
    border: 1px solid #00000045;
    font-size: 15px!IMPORTANT;
    margin: 9px 0px 0px 0px;
    }.from_city_link_layer span{
      font-size: 15px!IMPORTANT;
      font-weight: 500;
    }.where{
      width: 100%;
      padding: 15px ! IMPORTANT;
      border-radius: 9px;
      border: 1px solid #00000045;
      border: 1px solid #00000045;
      font-size: 15px ! IMPORTANT;
      margin: -15px 0px 25px 0px;
      height: 49px;
    }.where span{
      top: 5px;
      position: relative;
      margin: 0px 0px 0px 0px;
      font-size: 17px;
    }.form-date{
      display: flex;
      align-items: center;
    }
    .form-date div{margin: 0px 15px 0px 0px;}
    .form-date label{
      font-weight: 700;
      margin: 0px 15px 0px 0px;
    }.form-date input{
      padding: 9px 15px 9px 15px;
      border-radius: 15px;
      border: 2px solid #E1E1E1;
    }
    .create_travel_window_script .chosen-container{
      width: 100%;
      padding: 10px;
      border: 1px solid #E1E1E1;
      border-radius: 5px;
      font-size: 15px;
    }
    .chosen-container-multi .chosen-choices {
    position: relative;
    overflow: hidden;
    margin: 0;
    padding: 0 5px;
    width: 100%;
    height: auto;
    border: 1px solid #aaa;
    background-color: #fff;
    /* background-image: -webkit-gradient(linear, left top, left bottom, color-stop(1%, #eee), color-stop(15%, #fff)); */
    /* background-image: linear-gradient(#eee 1%, #fff 15%); */
    cursor: text;
    top: -9px;
}.chosen-container .chosen-drop {
    position: absolute;
    top: 100%;
    z-index: 1010;
    width: 100%;
    border: 1px solid #aaa;
    border-top: 0;
    background: #fff;
    -webkit-box-shadow: 0 4px 5px rgba(0, 0, 0, 0.15);
    box-shadow: 0 4px 5px rgba(0, 0, 0, 0.15);
    clip: rect(0, 0, 0, 0);
    -webkit-clip-path: inset(100% 100%);
    clip-path: inset(100% 100%);
    top: 15px!IMPORTANT;
}
    .where{
      /* {#padding: 0!IMPORTANT;#}
      {#margin: 0!IMPORTANT;#} */
    }
    .create_travel_window_script form .where{
      padding: 0!IMPORTANT;
      margin: 0!IMPORTANT;
    }
    .create_travel_window_script form .where{
      background-color: inherit;
      padding: 0!IMPORTANT;
      margin: 0!IMPORTANT;
    }
    .chosen-container-multi .chosen-choices{
      border: none!IMPORTANT;
      font-weight: 700;
    }.create_travel_window_script form textarea{
      font-family: 'Arial';
      font-size: 15px;
    }
  </style>
  </div>
</div>
<div class="where">
  <select name="country" id="id_country"  class="js-chosen3" style="" multiple required>
    <option value="" selected disabled>Куда?</option>
    {% for country in countries %}
    <option value="{{country.id}}">{{country.name}}</option>
    {% endfor %}
  </select>
  <!-- <label for="id_country" style="border-bottom: 1px solid rgb(225, 225, 225); padding: 0px 0px 9px; margin: 0px 0px 15px;">Куда</label>
  <div class="where-content-form">
    {% for country in countries_as %}
    <div>
      <input type="checkbox" name="country" id="{{country_id}}">
      <label for="{{country.id}}">{{country.name}}</label>
    </div>
    {% endfor %}
  </div> -->
</div>
<div class="form-city">
  <label for="id_city">Город, курорт</label>
  <input type="text" placeholder="Новосибирск" name="city" id="id_city" required></div>
  <div class="form-date">
    <div>
      <label for="">Когда</label>
      <input type="date" id="id_date" name="date" min="2018-01-01" max="3999-12-31" required>
    </div>
    <div>
      <label for="id_days">Кол-во дней</label>
      <input type="number" placeholder="15" style="max-width: 70px; text-align: center;" name="days" id="id_days" value="15" required>
    </div>
    {% comment %}
    <div style="flex-direction: row; align-items: center; margin: 25px 0px 0px;">
      <label for="" style="margin: 0px 15px 0px 0px;">Уже отдыхаю</label>
  <button class="relative inline-flex flex-shrink-0 border-2 border-transparent disabled:cursor-not-allowed disabled:opacity-50 focus:outline-none h-5 w-9 rounded-full focus-visible:ring-2 focus-visible:ring-primary-500 dark:focus-visible:ring-primary-400 focus-visible:ring-offset-2 focus-visible:ring-offset-white dark:focus-visible:ring-offset-gray-900 bg-gray-200 dark:bg-gray-700" role="switch" type="button" tabindex="0" aria-checked="false" data-headlessui-state="" id="nuid-2"><span class="pointer-events-none relative inline-block rounded-full bg-white dark:bg-gray-900 shadow transform ring-0 transition ease-in-out duration-200 h-4 w-4 translate-x-0 rtl:-translate-x-0">v-if<!--v-if--></span>
   </button> 
     </div>
     {% endcomment %}
  </div>
 <textarea name="description" id="id_description" cols="15" rows="2" placeholder="Опишите ваше путешествие ....." required></textarea>
 <p style="margin: 0px 0px 35px 0px;">
  <label for="id_travel_now">Уже путешествую:</label>
  <select name="travel_now" id="id_travel_now" required>
<option value="unknown">Неизвестно</option>

<option value="true">Да</option>

<option value="false" selected="">Нет</option>

</select>
  
  
</p> 
</div>
 <button type="submit">Опубликовать</button>
</form>
  </div>
</div>
<style>
  .base-content{
    background-color: inherit!IMPORTANT;
  }
  .create-trip-form{
    background-color: #FFFFFF;
    max-width: 779px;
    height: 79dvh;
  }

  .trip_form_layer_content{
    
    overflow: hidden;
    overflow-y: auto;
    height: 100%;
    padding: 0px 15px 0px 0px!IMPORTANT;

  }
    .road-view{display: flex;flex-wrap: wrap;gap: 15px;margin:0px 0px 25px 0px;}
    .road-view span{
        border-radius: 50px;
        border:1px solid #EBEBEB;
        padding: 9px 15px 9px 15px;
        min-width: max-content;
        display: flex;
        align-items: center;
        font-size: 17px;
    }
    .road-view span img{
        margin: 0px 5px 0px 0px;
    }

    @media (max-width: 770px){
    .index-friends-layout{
        margin: 0px auto 35px;
    }
    .index-friends-title{
        width: calc(100% -30px);
        flex-direction: column;
        align-items: flex-start;
        padding: 0px 0px 0px 15px;
    }
    .index-friends-title h2{
        font-size: 5vw;
    }
    .road-view{
        overflow: hidden;
        overflow-x: auto;
        display: grid;
        grid-template-columns: repeat(7, 1fr);
    grid-template-rows: repeat(2, auto);
    padding: 0px 15px 0px 15px;
    }
    .index-friends-user{
        margin: 0px 15px 0px 0px;
    }
    .index-friends-user img{
        max-width: 135px;
    }.index-friends-user p{
        font-size: 12px;
        padding: 0px;
        width: 100%;
        margin: 0px 0px 0px 0px;
    }
    .index-friends-users{
        padding: 0px 15px 0px 15px;
        margin: 0px 0px 35px 0px;
    }
}
</style>
{% endblock %}

templates/pages/create_trip.html
{% extends 'base_site.html' %}{% load static %}
{% block content %}

 <div class="wow animate__fadeInDown"></div>
 <form id="create_trip_window_script_form" action="{% url 'create_trip' %}" method="post" class="create-trip-form">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <h1>Создать поездку</h1>
  <div class="trip_form_layer_content">
  <div class="from-city">
  <label for="">Откуда едите?</label>
  <select name="city" id="id_city">
    <option value="" selected disabled>Выбирите город</option>
    {%for city in cities%}
    <option value="{{city.id}}">{{city.name}}</option>
    {%endfor%}
  </select>
</div>
  <div class="form-city">
  <label for="id_cityin" style="font-weight: 500;font-size:17px;">Куда едите?</label>
  <!-- <input type="text" placeholder="Новосибирск" name="city" id="id_city" required> -->
  <select name="cityin" id="id_cityin">
    <option value="" selected disabled>Выбирите город</option>
    {% for city in cities %}
    <option value="{{city.id}}">{{city.name}}</option>
    {% endfor %}
  </select>
</div>

  <div class="form-date">
    <div>
      <label for="id_trip_in_time">Дата начала поездки</label>
      <input type="datetime-local" id="id_date" name="trip_in_time" min="2018-01-01" max="3999-12-31" id="id_trip_in_time" required>
    </div>
    <div>
      <label for="id_trip_out_time">Дата прибытия</label>
      <input type="datetime-local" id="id_trip_out_time" name="trip_out_time" min="2018-01-01" max="3999-12-31" id="id_trip_out_time" required>
    </div>
    <div>
      <label for="id_free_seats">Количество мест</label>
      <input type="number" placeholder="2" style="max-width: 70px; text-align: center;" name="free_seats" id="id_days" value="0" id="id_free_seats" required>
    </div>
    <div>
      <label for="id_price">Цена за одно место, руб.</label>
      <input type="number" name="price" id="id_price" placeholder="200">
    </div>
    <div class="trip_others">
      <label for="id_trip_others">Условия поездки</label>
      {{trip_form.trip_others}}
    </div>
    <div class="trip_car">
      <label for="id_trip_car">Автомобиль</label>
      
      
      <select name="trip_car" id="id_trip_car">
        {% for car in request.user.cars.all %}
        <option value="{{car.car.id}}">{{car.car.name}}</option>
        {% endfor %}
      </select>
      
      
      
    </div>
  </div>
</div>
 <button type="submit">Опубликовать</button>
</form>
  </div>
</div>
<style>
  .base-content{
    background-color: inherit!IMPORTANT;
  }
  .create-trip-form{
    background-color: #FFFFFF;
    max-width: 779px;
    height: 79dvh;
  }

  .trip_form_layer_content{
    
    overflow: hidden;
    overflow-y: auto;
    height: 100%;
    padding: 0px 15px 0px 0px!IMPORTANT;

  }
    .road-view{display: flex;flex-wrap: wrap;gap: 15px;margin:0px 0px 25px 0px;}
    .road-view span{
        border-radius: 50px;
        border:1px solid #EBEBEB;
        padding: 9px 15px 9px 15px;
        min-width: max-content;
        display: flex;
        align-items: center;
        font-size: 17px;
    }
    .road-view span img{
        margin: 0px 5px 0px 0px;
    }

    @media (max-width: 770px){
    .index-friends-layout{
        margin: 0px auto 35px;
    }
    .index-friends-title{
        width: calc(100% -30px);
        flex-direction: column;
        align-items: flex-start;
        padding: 0px 0px 0px 15px;
    }
    .index-friends-title h2{
        font-size: 5vw;
    }
    .road-view{
        overflow: hidden;
        overflow-x: auto;
        display: grid;
        grid-template-columns: repeat(7, 1fr);
    grid-template-rows: repeat(2, auto);
    padding: 0px 15px 0px 15px;
    }
    .index-friends-user{
        margin: 0px 15px 0px 0px;
    }
    .index-friends-user img{
        max-width: 135px;
    }.index-friends-user p{
        font-size: 12px;
        padding: 0px;
        width: 100%;
        margin: 0px 0px 0px 0px;
    }
    .index-friends-users{
        padding: 0px 15px 0px 15px;
        margin: 0px 0px 35px 0px;
    }
}
</style>
{% endblock %}